### ISSUE TITLE
lineage 17 boot fail

### ISSUE THREAD

**Issue by mayingbin** [lineage-rpi/android_device_brcm_rpi4#2]
I got the image from https://konstakang.com/devices/rpi4/LineageOS17.1/.
But lineage boot fail，servicemanager crash. then the sevice reboot and crash again and again.

[   12.148726] init: starting service 'vendor.audio-hal-2-0'...
[   12.376677] type=1400 audit(9.559:75): avc: denied { map } for comm="crash_dump32" path="/dev/__properties__/u:object_r:hwservicemanager_prop:s0" dev="tmpfs" ino=8829 scontext=u:r:crash_dump:s0 tcontext=u:object_r:hwservicemanager_prop:s0 tclass=file permissive=1
[   12.400448] type=1400 audit(12.359:76): avc: denied { write } for comm="netd" name="tasks" dev="tmpfs" ino=10492 scontext=u:r:netd:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[   12.417695] type=1400 audit(12.359:76): avc: denied { write } for comm="netd" name="tasks" dev="tmpfs" ino=10492 scontext=u:r:netd:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[   12.434801] type=1400 audit(12.359:77): avc: denied { open } for comm="netd" path="/dev/stune/foreground/tasks" dev="tmpfs" ino=10492 scontext=u:r:netd:s0 tcontext=u:object_r:device:s0 tclass=file permissive=1
[   12.487629] init: starting service 'audioserver'...

[line17_fail.txt](https://github.com/lineage-rpi/android_device_brcm_rpi4/files/5266161/line17_fail.txt)

**Comment by KonstaT** [comment]
Could you run 'logcat' as well and post the output?

**Comment by mayingbin** [comment]
android boot not completely，init sub process crash，can't enter launcher app，no way to logcat.

**Comment by mayingbin** [comment]
Hi，KonstaT
Besides，how to support DSI connector the official display，do you have some idea？
I try lineage16 img，https://konstakang.com/devices/rpi4/LineageOS16.0/
boot successfully with the official 7“ display，anything config for dsi display?

**Comment by KonstaT** [comment]
KMS driver doesn't support DSI connector the official display panel uses. You would need to ask Pi Foundation what their plans are with this. It would have been worth pointing out you're using the official display.

Well, somehow you've managed to grab the dmesg. If you are using a serial console adapter, you can execute commands such as 'logcat' in the shell regardless if it boots to Android.

LineageOS 16.0 on the Pi 4 doesn't use KMS driver. It uses SwiftShader software renderer. Please read the FAQ on LineageOS 17.1 page on how to switch to using SwiftShader.

**Comment by mayingbin** [comment]
enn，thanks for your immediate reply，I will try SwiftShader.

**Comment by lubagov** [comment]
Hello! something similar.
I don't use MIPI DSI display now. Just write flash and try to boot.
But i use DVI display without audio support (Samsung SyncMaster 971P).
Also strange, why DSI display not support KMS? I use Eglfs-KMS and VC4 driver, with Qt application it normal working with DSI official 7" display.
RPI 4 B Rev 1.2 (UK),  lineage-18.1-20210104-UNOFFICIAL-KonstaKANG-rpi4.img
Thank you!
[logs.tar.gz](https://github.com/lineage-rpi/android_device_brcm_rpi4/files/5870124/logs.tar.gz)
