### ISSUE TITLE
Use external Dongle for Bluetooth

### ISSUE THREAD

**Issue by TheMasterRoot** [lineage-rpi/android_device_brcm_rpi4#6]
id like to know if is possible to use a usb bluetooth dongle instead of onboard raspberry p4 in lineage os android.

**Comment by KonstaT** [comment]
No, it's not possible like it's not possible on your regular Android phone/tablet. Android devices are basically embedded devices and the OS only needs to support certain specific piece of hardware.

Yes, it would likely be possible to create a separate build that supports bluetooth hardware X. Then the Pi's built-in bluetooth module woudn't work.
